/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Addmobile1.java
 *
 * 
 */

package mobilestorenew;

import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author 
 */
public class Addmobile1 extends javax.swing.JFrame {

    /** Creates new form Addmobile1 */
    String model,name,pcolor,date1,cbox="";
    
    int price,no,s1,s3,index,inc,inc1;
    String s2,imeino,mid,dpname,dpid,pname;
    
    int a=0,z=0,b=0,d=0;
    int count=0;int prevalue=0,curvalue;
    

    public Addmobile1()
    {
        initComponents();
        setVisible(true);
        setSize(1270,740);
        
        setTitle("Add Mobile Phone Details");
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
    
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);
        jComboBox4.setEnabled(false);
        jComboBox5.setEnabled(false);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);
        jButton4.setEnabled(false);
        jButton3.setEnabled(false);
        
    }
   
     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Mobile Phone Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 0, 303, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Mobile Phone Id");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(50, 20, 130, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Mobile Phone Color");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(50, 70, 190, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Enter IMEI Number");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(50, 120, 160, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Enter Date Of Manufacture");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(50, 170, 190, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Additional Accessories");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(50, 230, 170, 30);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(250, 20, 140, 30);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(250, 120, 140, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText(" SAVE PHONE DETAILS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(90, 330, 240, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(410, 120, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(410, 20, 100, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green", "Blue", "Black", "White", "Cyan", "Yellow", "Orange", "Purple", "Pink", "Voilet", "Magenta" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(250, 70, 140, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Charger ");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(250, 240, 80, 23);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setText("HeadSet ");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(360, 240, 80, 23);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setText("DataCable ");
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(460, 240, 100, 23);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox4.setText("Battery ");
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(250, 280, 80, 23);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox5.setText("MemoryCard ");
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(360, 280, 101, 23);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox6.setText("CD ");
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(470, 280, 50, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(370, 330, 110, 50);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(250, 180, 50, 30);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(330, 180, 56, 30);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jComboBox5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox5FocusLost(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(426, 180, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("(DD)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 180, 30, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("(MM)");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(390, 180, 32, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("(YY)");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(490, 180, 30, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 290, 570, 400);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Price");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 120, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("No. of Mobile Phones");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 170, 150, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nokia", "Samsung", "Lava", "MaxMobile", "Itel", "Vediocon", "Gionee", "Oppo", "Vivo", "Panasonic", "Intex", "Xolo", "Mi", "Micromax", "iBall", "Honor" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(250, 20, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mobile Phone Model");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 20, 150, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(250, 70, 140, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(250, 120, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Enter Mobile Name");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 70, 160, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(250, 170, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(410, 70, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(410, 120, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(410, 170, 100, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(200, 60, 570, 220);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enter each Phone Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 130, 210, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        if(jTextField2.getText().equals(""))
        {
            jLabel8.setText("Entry Is Must");
            jTextField2.setText("");
        } 
        else
        {
            jLabel8.setText("");
            try
            {

                name=jTextField2.getText();
                Connection co;
            Statement st;
            Class.forName("com.mysql.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
            st = co.createStatement();
                ResultSet res=st.executeQuery("select * from newmobile_details");
                Boolean rec=res.next();
                if(!rec)
                {

                }
                else
                {
                    do
                    {
                        String nm=res.getString(3);
                        if(name.equals(nm))
                        {
                            jTextField3.setText(Integer.toString(res.getInt(4)));
                            
                        }
                    }while(res.next());
                    

                }
                st.close();
              
                    co.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is :1"+e);
            }
        }
}//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        if(jTextField3.getText().equals(""))
        {
            jLabel9.setText("Entry Is Must") ;
            jTextField3.setText("");
        }

        else
        {
            String jtf1=jTextField3.getText();
            int fg=0;
            for(int i=0;i<jtf1.length();i++)
            {
                char c=jtf1.charAt(i);
                if(Character.isLetter(c))
                {
                    fg=0;
                    break;
                }
                else
                {
                    fg=1;
                    
                }
            }
            if(fg==0)
            {
                jLabel9.setText("Enter Numbers") ;
                jTextField3.setText("");
            }
            else
                jLabel9.setText("") ;
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if(jTextField2.getText().equals("") || jTextField3.getText().equals("") || jTextField4.getText().equals("")) {

            JOptionPane.showMessageDialog(null,"Enter all appropriate fields");
            
            if(jTextField2.getText().equals("")) {
                jLabel8.setText("Fill this field");
            } else {
                jLabel8.setText("");
            }
            if(jTextField3.getText().equals("")) {
                jLabel9.setText("Fill this field");

            } else {
                jLabel9.setText("");
            }
            if(jTextField4.getText().equals("")) {
                jLabel10.setText("Fill this field");
            } else {
                jLabel10.setText("");
            }

        } 
        else
        {
            no=Integer.parseInt(jTextField4.getText());
            if(count<no)
            {
                jComboBox1.setEnabled(false);
                jTextField2.setEditable(false);
                jTextField3.setEditable(false);
                jTextField4.setEditable(false);
                jButton1.setEnabled(false);
                
                JOptionPane.showMessageDialog(null,"Enter First Mobile Phone Details");
                jTextField6.setEditable(true);
                jComboBox2.setEnabled(true);
                jComboBox3.setEnabled(true);
                jComboBox4.setEnabled(true);
                jComboBox5.setEnabled(true);
                jCheckBox1.setEnabled(true);
                jCheckBox2.setEnabled(true);
                jCheckBox3.setEnabled(true);
                jCheckBox4.setEnabled(true);
                jCheckBox5.setEnabled(true);
                jCheckBox6.setEnabled(true);
                jButton4.setEnabled(true);
                jButton3.setEnabled(true);

            }
            else
            {
                JOptionPane.showMessageDialog(null,"enter No. of Mobiles as 1 or more");
                jTextField4.setText("");
            }

            //extra requirement code
            try
            {
                pname=jTextField2.getText();
                Connection co;
            Statement st;
            Class.forName("com.mysql.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
            st = co.createStatement();
                ResultSet res=st.executeQuery("select * from newmobile_details");
                Boolean rec=res.next();
                if(!rec)
                {
                    mid=jTextField2.getText();
                    mid+="-";
                    mid+="1";
                    jTextField5.setText(mid);
                }
                else
                {
                    do
                    {
                        dpid=res.getString(1);
                        dpname=res.getString(3);
                        if(pname.equalsIgnoreCase(dpname))
                        {
                            System.out.println(dpid);

                            index=dpid.indexOf("-");

                            System.out.println(index);

                            curvalue=Integer.parseInt(dpid.substring(index+1));

                            if(prevalue<curvalue)
                            {
                                inc=curvalue+1;
                                prevalue=curvalue;
                            }
                                                        
                            mid=jTextField2.getText();
                            mid+="-";
                            mid+=Integer.toString(inc);
                            jTextField5.setText(mid);
                            b=1;
                            
                        }

                    }while(res.next());

                    if(b==0)
                    {
                        mid=jTextField2.getText();
                        mid+="-";
                        mid+="1";
                        jTextField5.setText(mid);
                    }
                }
                st.close();
                   
                    co.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is:2"+e);
            }
            //extra requirement code ends here
            
       }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        if(jTextField4.getText().equals(""))
        {
            jLabel10.setText("Entry Is Must") ;
            jTextField4.setText("");
        }

        else
        {
            String jtf1=jTextField4.getText();
            int fg=0;
            for(int i=0;i<jtf1.length();i++)
            {
                char c=jtf1.charAt(i);
                if(Character.isLetter(c))
                {
                    fg=0;
                    break;
                }
                else
                {
                    fg=1;
                    
                }
            }
            if(fg==0)
            {
                jLabel10.setText("Enter Numbers") ;
                jTextField4.setText("");
            }
            else
                jLabel10.setText("") ;
                
        }
}//GEN-LAST:event_jTextField4FocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTextField5.getText().equals("") || jTextField6.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter all appropriate fields");
            if(jTextField5.getText().equals(""))
            {
                jLabel11.setText("Fill this field");

            }
            else
            {
                jLabel11.setText("");
            }
            if(jTextField6.getText().equals(""))
            {
                jLabel12.setText("Fill this field");

            }
            else
            {
                jLabel12.setText("");
            }
            
        }
        else
        {
            
            name=jTextField2.getText();
            model=(String)jComboBox1.getSelectedItem();
            price=Integer.parseInt(jTextField3.getText());
            
            pcolor=(String)jComboBox2.getSelectedItem();
            imeino=jTextField6.getText();
            
            date1=(String)jComboBox3.getSelectedItem();
            date1+="-";
            date1+=(String)jComboBox4.getSelectedItem();
            date1+="-";
            date1+=(String)jComboBox5.getSelectedItem();

            
            cbox="";
            Boolean temp=(Boolean)jCheckBox1.isSelected();
            if(temp==true)
            {
                cbox+=(String)jCheckBox1.getText();
            }
            
            Boolean temp1=(Boolean)jCheckBox2.isSelected();
            if(temp1==true)
            {
                cbox+=(String)jCheckBox2.getText();
            }

            Boolean temp2=(Boolean)jCheckBox3.isSelected();
            if(temp2==true)
            {
                cbox+=(String)jCheckBox3.getText();
            }

            Boolean temp3=(Boolean)jCheckBox4.isSelected();
            if(temp3==true)
            {
                cbox+=(String)jCheckBox4.getText();
            }

            Boolean temp4=(Boolean)jCheckBox5.isSelected();
            if(temp4==true)
            {
                cbox+=(String)jCheckBox5.getText();
            }

            Boolean temp5=(Boolean)jCheckBox6.isSelected();
            if(temp5==true)
            {
                cbox+=(String)jCheckBox6.getText();
            }
            
            System.out.println(cbox);
            try
            {
                Connection co;
            Statement st;
            Class.forName("com.mysql.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
            st = co.createStatement();
                System.out.println("connected successfully");
                String pr=Integer.toString(price);
               int res=st.executeUpdate("insert into newmobile_details values("+"'"+mid+"'"+","+"'"+model+"'"+","+"'"+name+"'"+","+"'"+pr+"'"+","+"'"+pcolor+"'"+","+"'"+imeino+"'"+","+"'"+date1+"'"+","+"'"+cbox+"'"+")");
                if(count<no)
                {
                        
                                        
                        
                       //prp.setString(1,mid);
                        //prp.setString(2,model);
                        //prp.setString(3,name);
                        //prp.setString(4,Integer.toString(price));
                        //prp.setString(5,pcolor);
                        //prp.setString(6,imeino);
                        //prp.setString(7,date1);
                        //prp.setString(8,cbox);
                        
                        //prp.executeUpdate();

                        JOptionPane.showMessageDialog(null,"Mobiele Phone details saved successfully");

                        
                        jTextField6.setText("");

                        jComboBox2.setSelectedItem("Red");
                        jComboBox3.setSelectedItem("01");
                        jComboBox4.setSelectedItem("jan");
                        jComboBox5.setSelectedItem("2000");

                        jCheckBox1.setSelected(false);
                        jCheckBox2.setSelected(false);
                        jCheckBox3.setSelected(false);
                        jCheckBox4.setSelected(false);
                        jCheckBox5.setSelected(false);
                        jCheckBox6.setSelected(false);

                        cbox="";
                        
                        

                        count++;
                        //extra requirement code starts from here

                        index=jTextField5.getText().indexOf("-");
                        System.out.println(index);
                        inc1=Integer.parseInt(jTextField5.getText().substring(index+1));
                        inc1++;
                        System.out.print(inc1);
                        mid=jTextField2.getText();
                        mid+="-";
                        mid+=Integer.toString(inc1);
                        jTextField5.setText(mid);

                        //ends here

                        if(count<no)
                        {
                            JOptionPane.showMessageDialog(null,"Enter Next Mobile Phone Details");
                        }
                        if(count>=no)
                        {
                            
                            count=0;
                            
                            jComboBox1.setEnabled(true);
                            jTextField2.setEditable(true);
                            jTextField3.setEditable(true);
                            jTextField4.setEditable(true);
                            jButton1.setEnabled(true);
                            
                            jTextField6.setEditable(false);
                            jComboBox2.setEnabled(false);
                            jCheckBox1.setSelected(false);
                            jCheckBox2.setSelected(false);
                            jCheckBox3.setSelected(false);
                            jCheckBox4.setSelected(false);
                            jCheckBox5.setSelected(false);
                            jCheckBox6.setSelected(false);

                            jComboBox1.setSelectedItem("Nokia");
                            jComboBox2.setSelectedItem("Red");
                            jComboBox3.setSelectedItem("1");
                            jComboBox4.setSelectedItem("jan");
                            jComboBox5.setSelectedItem("2000");

                            jComboBox2.setEnabled(false);
                            jComboBox3.setEnabled(false);
                            jComboBox4.setEnabled(false);
                            jComboBox5.setEnabled(false);
                            jButton4.setEnabled(false);
                            jButton3.setEnabled(false);

                            jTextField2.setText("");
                            jTextField3.setText("");
                            jTextField4.setText("");
                            jTextField5.setText("");
                            jTextField6.setText("");

                            jCheckBox1.setEnabled(false);
                            jCheckBox2.setEnabled(false);
                            jCheckBox3.setEnabled(false);
                            jCheckBox4.setEnabled(false);
                            jCheckBox5.setEnabled(false);
                            jCheckBox6.setEnabled(false);


                        }
                      
                }

                  
                    co.close();
                
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,"INVALID DATE, ple  select correct date3"+e);
                jComboBox3.setSelectedItem("01");
                jComboBox4.setSelectedItem("jan");
                jComboBox5.setSelectedItem("2000");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is4:"+e);
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        count=0;

        jComboBox1.setSelectedItem("Nokia");
        jComboBox1.setEnabled(true);
        jTextField2.setEditable(true);
        jTextField3.setEditable(true);
        jTextField4.setEditable(true);
        jButton1.setEnabled(true);
        
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");

        jComboBox2.setSelectedItem("Red");
        jComboBox3.setSelectedItem("01");
        jComboBox4.setSelectedItem("jan");
        jComboBox5.setSelectedItem("2000");

        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);

        jTextField6.setEditable(false);
        jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);
        jComboBox4.setEnabled(false);
        jComboBox5.setEnabled(false);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);
        jButton4.setEnabled(false);
        jButton3.setEnabled(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:
        if(jTextField6.getText().equals(""))
        {
            jLabel12.setText("Entry Is Must");
        }
        else
        {
            String jtf1=jTextField6.getText();
            int fg=0;
            for(int i=0;i<jtf1.length();i++)
            {
                char c=jtf1.charAt(i);
                if(Character.isLetter(c))
                {
                    fg=0;
                    break;
                }
                else
                {
                    fg=1;
                    
                }
            }
            if(fg==0)
            {
                jLabel12.setText("Enter Numbers") ;
                jTextField6.setText("");
            }
            else
            {
                jLabel12.setText("");
            }

                String imei=jTextField6.getText();
                try
                {
                   Connection co;
            Statement st;
            Class.forName("com.mysql.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
            st = co.createStatement();
                    ResultSet res=st.executeQuery("select * from newmobile_details");
                    Boolean rec=res.next();
                    if(!rec)
                    {

                    }
                    else
                    {
                        do
                        {
                            String dimei=res.getString(6);
                            if(imei.equals(dimei))
                            {
                                JOptionPane.showMessageDialog(null,"The Mobile Phone is already in the database");
                                jTextField6.setText("");
                                jLabel12.setText("");
                            }
                        }while(res.next());
                    }
                    st.close();
                   
                    co.close();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"The error is5"+e);
                }
                

        }
    }//GEN-LAST:event_jTextField6FocusLost

    private void jComboBox5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox5FocusLost
        // TODO add your handling code here:
        String temp1=(String)jComboBox5.getSelectedItem();
        int useryear=Integer.parseInt(temp1);
        Date curyear=new Date();
        String temp2=curyear.toString();
        temp2=temp2.substring(24,28);
        int cyear=Integer.parseInt(temp2);

        if(useryear>cyear)
        {
            JOptionPane.showMessageDialog(null,"The Manufacture Date should be on (or) before this year");
            jComboBox5.setSelectedItem("2000");
        }

    }//GEN-LAST:event_jComboBox5FocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addmobile1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
