/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BillGeneration.java
 *
 * 
 */

package mobilestorenew;

import java.sql.*;
import javax.swing.*;
import java.util.Date;

/**
 *
 * 
 */
public class BillGeneration extends javax.swing.JFrame {

    /** Creates new form BillGeneration */

    Date dat;
    int bid,reply;
    int a=0,b=0,c=0,d=0,x=0;
    String dt,year,month,day,date;
    int price=0,amtpaid,balamt,dpaidamt,dbalamt,drefid,dage;
    String text="",cid="r",dcid,dcname,year1,month1,day1,mc1,dt1,dgender;
    String cname,mob_purchased,ddno,dstreet,dcity,dstate,dphno;
    int flag=0;
    String s1,s2,s3,s4,nameappend="";
    int addprice;

    public BillGeneration() {
        initComponents();
        setVisible(true);
        setSize(1270,740);
        setTitle("Generate Bill");
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField6.setEditable(false);
        idincrement();
        jTextField6.setText(Integer.toString(price));
      
    }
    public void idincrement()
    {
        try
        {

            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            //Connection co=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
            Connection co;
            Statement st;
            Class.forName("com.mysql.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
            st = co.createStatement();
            ResultSet res=st.executeQuery("select * from newbill");
            while(res.next())
            {
                bid=Integer.parseInt(res.getString(1));
            }
            
            st.close();
            co.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"the error is 1"+e);
            System.out.println(e.getMessage());
        }
            bid=bid+1;
            jTextField1.setText(Integer.toString(bid));
            
            dat=new Date();
            dt=dat.toString();
            System.out.println(dt);
            day=dt.substring(8,10);
            month=dt.substring(4,7);
            year=dt.substring(24,28);


            date=day;
            date+="-";
            date+=month;
            date+="-";
            date+=year;

            jTextField2.setText(date);

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Generate Bill");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 20, 220, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bill Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 80, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bill Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 130, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Customer Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 180, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Added Mobiles");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 400, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(280, 530, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Amount Paid");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 580, 110, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Generate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 640, 160, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(460, 80, 130, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(460, 130, 130, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(460, 180, 130, 30);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(460, 530, 130, 30);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(460, 580, 130, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(9);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 400, 410, 110);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 280, 100, 40);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(580, 180, 120, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Select Phone Model");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 20, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Enter Phone Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 70, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Enter IMEI Number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 120, 180, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(220, 70, 130, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nokia", "Samsung", "Lava", "MaxMobile", "Itel", "Vediocon", "Gionee", "Oppo", "Vivo", "Panasonic", "Intex", "Xolo", "Mi", "Micromax", "iBall", "Honor" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(220, 20, 130, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(360, 70, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(360, 120, 100, 30);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(220, 120, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(240, 220, 480, 170);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(600, 580, 100, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(600, 530, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        if(jTextField3.getText().equals(""))
        {
            jLabel11.setText("Entry Is Must") ;
            jTextField3.setText("");
        }

        else
        {
            jLabel11.setText("") ;
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        if(jTextField4.getText().equals(""))
        {
            jLabel12.setText("Entry Is Must");
        }
        else
        {
            jLabel12.setText("");
        
            String name=jTextField4.getText();
            String model=(String) jComboBox1.getSelectedItem();
            try
            {
                //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                //Connection con=DriverManager.getConnection("Jdbc:Odbc:mobileDSN","scott","tiger");
                Connection co;
                    Statement st;
                    Class.forName("com.mysql.jdbc.Driver");
                    co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                    st = co.createStatement();

                ResultSet res=st.executeQuery("select * from newmobile_details");
                Boolean rec=res.next();
                if(!rec)
                {
                    JOptionPane.showMessageDialog(null,"There are no Mobile phones in database");

                }
                else
                {
                    do
                    {
                        String s11=res.getString(2);
                        String s22=res.getString(3);

                        if(model.equalsIgnoreCase(s11) && name.equalsIgnoreCase(s22))
                        {
                               b=1;
                        }

                    }while(res.next());
                    if(b==0)
                    {
                        JOptionPane.showMessageDialog(null,"The mobile phone is not available, Please purchase another one");
                        jTextField4.setText("");
                        jLabel12.setText("Entry Is Must");


                    }
                }
               
                co.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is:2 "+e);
            }
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        // TODO add your handling code here:
        b=0;
        
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        if(jTextField5.getText().equals(""))
        {
            jLabel13.setText("Entry is Must");
        }
        else
        {
            String jtf1=jTextField5.getText();
            int fg=0;
            for(int i=0;i<jtf1.length();i++)
            {
                char c1=jtf1.charAt(i);
                if(Character.isLetter(c1))
                {
                    fg=0;
                    break;
                }
                else
                {
                    fg=1;

                }
            }
            if(fg==0)
            {
                jLabel13.setText("Enter Numbers") ;
                jTextField5.setText("");
            }
            else
            {
                jLabel13.setText("") ;
            }
            try
            {
                String imeino=jTextField5.getText();
                //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                Connection co;
                Statement st;
                Class.forName("com.mysql.jdbc.Driver");
                co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                st = co.createStatement();
                ResultSet res=st.executeQuery("select * from newmobile_details");
                Boolean rec=res.next();
                if(!rec)
                {
                    JOptionPane.showMessageDialog(null,"There are no Mobile phones in database");

                }
                else
                {
                    do
                    {
                        String s12=res.getString(6);
                        if(imeino.equals(s12))
                        {
                            c=1;
                        }
                    }while(res.next());
                    if(c==0)
                    {
                        JOptionPane.showMessageDialog(null,"The mobile phone is not available, Please purchase another one");
                        jTextField5.setText("");
                        jLabel13.setText("Entry is Must");
                    }
                }
                st.close();
                co.close();

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is:3"+e);
            }
        }
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
        c=0;
    }//GEN-LAST:event_jTextField5FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        x=0;
            if(jTextField4.getText().equals("") || jTextField5.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Enter All appropriate fields");
                if(jTextField4.getText().equals(""))
                {
                    jLabel12.setText("Fill this Field");
                }
                else
                {
                    jLabel12.setText("");
                }
                if(jTextField5.getText().equals(""))
                {
                    jLabel13.setText("Fill this Field");
                }
                else
                {
                    jLabel13.setText("");
                }
            }
            else
            {
                try
                {

                    String model=(String)jComboBox1.getSelectedItem();
                    String name=jTextField4.getText();
                    String imeino=jTextField5.getText();

                    //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                   Connection co;
                    Statement st;
                    Class.forName("com.mysql.jdbc.Driver");
                    co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                    st = co.createStatement();

                    ResultSet res=st.executeQuery("select * from newmobile_details");
                    Boolean rec=res.next();
                    if(!rec)
                    {
                        JOptionPane.showMessageDialog(null,"There are no Mobile phones in database");
                        jTextField4.setText("");
                        jTextField5.setText("");

                    }
                    else
                    {
                        do
                        {
                             s1=res.getString(2);
                             s2=res.getString(3);
                             addprice=Integer.parseInt(res.getString(4));
                             s3=res.getString(5);
                             s4=res.getString(6);
                             
                            if(s1.equalsIgnoreCase(model) && s2.equalsIgnoreCase(name) && s4.equalsIgnoreCase(imeino))
                            {

                                int reply2=JOptionPane.showConfirmDialog(null,"Are Sure You Want to Purchase");
                                if(reply2==JOptionPane.YES_OPTION)
                                {

                                        price=addprice;
                                        jTextField6.setText(Integer.toString(price));

                                        text+="\n"+s2+"\t"+Integer.toString(addprice)+"\t"+s3+"\t"+s4;
                                        System.out.println(text);

                                        jTextArea1.setText("Phone Name \tPhone Price \tPhone Color \tIMEI Number \n-------" +
                                        "--------------------------------------------------------------------------"+text);
                                    
                                        //PreparedStatement prp=con.prepareStatement("delete * from newmobile_details where imeino="+"'"+s4+"'");
                                        //prp.executeUpdate();
                                        System.out.println(s4);
                                        Statement prp1=co.createStatement();
                        //ResultSet prp=prp1.executeQuery("update newcutomer_details set pdate="+"'"+date1+"'"+","+"paidamt="+"'"+spmt+"'"+'","+balamt="+"'"+stbal+"'"" where cid="+"'"+sid+"'"+");
                        int prp=prp1.executeUpdate("delete from newmobile_details where imeino="+"'"+s4+"'");
                        System.out.println(prp);
                                        nameappend+=s2+", ";
                                        System.out.println(nameappend);
                                        jComboBox1.setSelectedItem("nokia");
                                        jTextField4.setText("");
                                        jTextField5.setText("");
                                        x=1;

                                }
                                if(reply2==JOptionPane.NO_OPTION)
                                {
                                        jComboBox1.setSelectedItem("nokia");
                                        jTextField4.setText("");
                                        jTextField5.setText("");
                                }
                                if(reply2==JOptionPane.CANCEL_OPTION)
                                {
                                        jComboBox1.setSelectedItem("nokia");
                                        jTextField4.setText("");
                                        jTextField5.setText("");
                                }

                            }
                        }while(res.next());
                        if(x==0)
                        {
                            JOptionPane.showMessageDialog(null,"The Model and Name and IMEI No does not match, please enter correctly");
                        }
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"The error is:4"+e);
                }
            }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(flag==0)
        {
            if(jTextField3.getText().equals("") || jTextField6.getText().equals("0") || jTextField7.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Enter all appropriate fields");
                if(jTextField3.getText().equals(""))
                {
                    jLabel11.setText("Fill this Field");
                }
                else
                {
                    jLabel11.setText("");
                }
                if(jTextField6.getText().equals("0"))
                {
                    jLabel14.setText("Please Add Mobile Phone");
                }
                else
                {
                    jLabel14.setText("");
                }
                if(jTextField7.getText().equals(""))
                {
                    jLabel15.setText("Fill this field");
                }
                else
                {
                    jLabel15.setText("");
                }
            }
            else
            {
                cname=jTextField3.getText();
                mob_purchased=text;
                amtpaid=Integer.parseInt(jTextField7.getText());
                balamt=price-amtpaid;
                try
                {
                    //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                   Connection co;
                    Statement st;
                    Class.forName("com.mysql.jdbc.Driver");
                    co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                    st = co.createStatement();

                    PreparedStatement prp=co.prepareStatement("insert into newbill values(?,?,?,?,?,?,?)");
                    prp.setString(1,Integer.toString(bid));
                    prp.setString(2,date);
                    prp.setString(3,cname);
                    prp.setString(4,Integer.toString(price));
                    prp.setString(5,Integer.toString(amtpaid));
                    prp.setString(6,mob_purchased);
                    prp.setString(7,nameappend);
                    
                    prp.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Bill details successfully saved");

                    PrintPreview pp=new PrintPreview();
                    pp.jLabel3.setText(Integer.toString(bid));
                    pp.jLabel5.setText(date);
                    pp.jLabel7.setText(cname);
                    pp.jTextArea1.setText("Phone Name \tPhone Price \tPhone Color \tIMEI Number \n-------" +
                    "--------------------------------------------------------------------------"+text);
                    pp.jLabel11.setText(Integer.toString(price));
                    pp.jLabel13.setText(Integer.toString(amtpaid));
                    pp.text=text;
                    pp.flag=0;
                                
                    price=0;
                    bid++;
                    text="-";
                    jTextField1.setText(Integer.toString(bid));
                    jTextField3.setText("");
                    jTextArea1.setText("");
                    jTextField6.setText("0");
                    jTextField7.setText("");

  
                    co.close();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"The error is:5"+e);
                }

            }
        }
        if(flag==1)
        {
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
        int amtcheck=Integer.parseInt(jTextField7.getText());
        if(amtcheck>price)
        {
            jTextField7.setText("");
            JOptionPane.showMessageDialog(null,"The Bill Amount is:"+price+", So pay less than or equal to the amount");
        }
    }//GEN-LAST:event_jTextField7FocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillGeneration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
