/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreditCustomer.java
 *
 * 
 */

package mobilestorenew;

import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;


/**
 *
 * 
 */
public class CreditCustomer extends javax.swing.JFrame {

    /** Creates new form CreditCustomer */
    int cid,paidamt,balamt,refid,age,currentcid;
    String sex="Male";
    String cname,pdate,dob,dno,street,city,state,phno,mob_purchased,year;
    int flag,totalbal,prevalue=0,curvalue;
    String dat;
    public CreditCustomer() {
        initComponents();
        setVisible(true);
        setSize(1270,740);
        setTitle("Credit Customer");
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField13.setEditable(false);
        jTextField14.setEditable(false);
        jTextArea1.setEditable(false);

        idincrement();

        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
    }
   
    public void idincrement()
    {
        try
        {

            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            //Connection co=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
            Connection co;
            Statement st;
            Class.forName("com.mysql.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
            st = co.createStatement();
            //ResultSet res=st.executeQuery("select curdat()");
            DateFormat sdf = new SimpleDateFormat("dd/mm/yyyy");
            Date date=new Date();
            dat=sdf.format(date);
            ResultSet res=st.executeQuery("select * from newcustomer_details");
            Boolean rec=res.next();
            if(!rec)
            {
                cid=1;
            }
            else
            {
                do
                {
                    curvalue=Integer.parseInt(res.getString(1));
                    if(prevalue<curvalue)
                    {
                        cid=curvalue+1;
                        prevalue=curvalue;
                    }

                }while(res.next());
            }

            st.close();
            co.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"the error is"+e);
        }
        
        jTextField1.setText(Integer.toString(cid));

        /*year=dat;
        year=year.substring(0,4);
        System.out.println(dob);*/
        
    }
    public void saveupdate()
    {
                dob=(String)jComboBox1.getSelectedItem();
                dob+="-";
                dob+=(String)jComboBox2.getSelectedItem();
                dob+="-";
                dob+=(String)jComboBox3.getSelectedItem();
                System.out.println(dob);
                //int a=(Integer.parseInt(year)-Integer.parseInt(jComboBox3.getSelectedItem().toString()))-1;
                //jTextField7.setText(Integer.toString(a));
                age=Integer.parseInt(jTextField7.getText());
                dno=jTextField8.getText();
                street=jTextField9.getText();
                city=jTextField10.getText();
                state=jTextField11.getText();
                phno=jTextField12.getText();
                mob_purchased=jTextArea1.getText();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabe = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("Add Credit Customer Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 0, 350, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Age");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(480, 30, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Gender");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 90, 110, 30);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(130, 90, 60, 30);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(210, 90, 70, 30);

        jLabe.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabe.setText("City");
        jPanel2.add(jLabe);
        jLabe.setBounds(480, 140, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Door NO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(480, 90, 110, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setText("Street");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 140, 80, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setText("State");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 200, 80, 30);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jPanel2.add(jTextField7);
        jTextField7.setBounds(580, 30, 160, 30);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });
        jPanel2.add(jTextField9);
        jTextField9.setBounds(130, 140, 170, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel14.setText("Phone Number");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(480, 200, 100, 30);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });
        jPanel2.add(jTextField10);
        jTextField10.setBounds(580, 140, 160, 30);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jPanel2.add(jTextField8);
        jTextField8.setBounds(580, 90, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Date of Birth");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 30, 90, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel16.setText("(DD)");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(180, 30, 30, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(210, 30, 56, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel17.setText("(MM)");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(270, 30, 40, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995" }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(310, 30, 60, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel18.setText("(YY)");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(370, 30, 30, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(130, 30, 50, 30);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });
        jPanel2.add(jTextField11);
        jTextField11.setBounds(130, 200, 170, 30);

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });
        jPanel2.add(jTextField12);
        jTextField12.setBounds(580, 200, 160, 30);
        jPanel2.add(jLabel19);
        jLabel19.setBounds(750, 30, 170, 30);
        jPanel2.add(jLabel20);
        jLabel20.setBounds(750, 90, 170, 30);
        jPanel2.add(jLabel21);
        jLabel21.setBounds(310, 140, 110, 30);
        jPanel2.add(jLabel23);
        jLabel23.setBounds(310, 200, 120, 30);
        jPanel2.add(jLabel24);
        jLabel24.setBounds(750, 200, 170, 30);
        jPanel2.add(jLabel22);
        jLabel22.setBounds(750, 140, 160, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 370, 980, 250);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(170, 30, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Customer Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Customer Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 30, 120, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(490, 30, 170, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Date Purchased");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 80, 100, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(170, 80, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Mobiles Purchased");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 130, 120, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(9);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(490, 130, 410, 170);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setText("Paid Amount");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 80, 100, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(490, 80, 170, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setText("Balance Amount");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 130, 100, 30);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(170, 130, 140, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setText("Reference Id");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 180, 100, 30);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(170, 180, 140, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setText("Old Balance Amount");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(30, 230, 130, 30);

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPanel1.add(jTextField13);
        jTextField13.setBounds(170, 230, 140, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel26.setText("Total Balance Amount");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(30, 280, 140, 30);

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPanel1.add(jTextField14);
        jTextField14.setBounds(170, 280, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 980, 320);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setText("Save Customer Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(150, 10, 210, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(370, 10, 100, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(180, 630, 610, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
        if(jTextField7.getText().equals(""))
        {
            jLabel19.setText("Entry Is Must");
        }
        else if(jTextField7.getText().length()>2)
        {
            jLabel19.setText("Enter Valid Age");
            jTextField7.setText("");
        }
        else
        {
            String jtf1=jTextField7.getText();
            int fg=0;
            for(int i=0;i<jtf1.length();i++)
            {
                char c1=jtf1.charAt(i);
                if(Character.isLetter(c1))
                {
                    fg=0;
                    break;
                }
                else
                {
                    fg=1;
                }
            }
            if(fg==0)
            {
                jLabel19.setText("Enter Numbers");
                jTextField7.setText("");
            }
            else
                jLabel19.setText("") ;
        }
    }//GEN-LAST:event_jTextField7FocusLost

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        sex="Male";
        System.out.println(sex);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        sex="Female";
        System.out.println(sex);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        // TODO add your handling code here:
        if(jTextField8.getText().equals(""))
        {
            jLabel20.setText("Entry Is Must");
        }
        else
        {
            jLabel20.setText("");
        }
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        // TODO add your handling code here:
        if(jTextField9.getText().equals(""))
        {
            jLabel21.setText("Entry Is Must");
        }
        else
        {
            jLabel21.setText("");
        }
    }//GEN-LAST:event_jTextField9FocusLost

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        // TODO add your handling code here:
        if(jTextField10.getText().equals(""))
        {
            jLabel22.setText("Entry Is Must");
        }
        else
        {
            jLabel22.setText("");
        }
    }//GEN-LAST:event_jTextField10FocusLost

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:
        if(jTextField11.getText().equals(""))
        {
            jLabel23.setText("Entry Is Must");
        }
        else
        {
            jLabel23.setText("") ;
        }
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
        // TODO add your handling code here:
        if(jTextField12.getText().equals(""))
        {
            jLabel24.setText("Entry Is Must");
        }
        else
        {
            String jtf1=jTextField12.getText();
            int fg=0;
            for(int i=0;i<jtf1.length();i++)
            {
                char c1=jtf1.charAt(i);
                if(Character.isLetter(c1))
                {
                    fg=0;
                    break;
                }
                else
                {
                    fg=1;
                }
            }
            if(fg==0)
            {
                jLabel24.setText("Enter Valid Phone Number");
                jTextField12.setText("");
            }
            else
                jLabel24.setText("") ;
        }
    }//GEN-LAST:event_jTextField12FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField7.getText().equals("") || jTextField8.getText().equals("") || jTextField9.getText().equals("") || jTextField10.getText().equals("") || jTextField11.getText().equals("") || jTextField12.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter all appropriate fields");
            if(jTextField7.getText().equals(""))
            {
                jLabel19.setText("Fill this Field");
            }
            else
                jLabel19.setText("");
            if(jTextField8.getText().equals(""))
            {
                jLabel20.setText("Fill this Field");
            }
            else
                jLabel20.setText("");
            if(jTextField9.getText().equals(""))
            {
                jLabel21.setText("Fill this Field");
            }
            else
                jLabel21.setText("");
            if(jTextField10.getText().equals(""))
            {
                jLabel22.setText("Fill this Field");
            }
            else
                jLabel22.setText("");
            if(jTextField11.getText().equals(""))
            {
                jLabel23.setText("Fill this Field");
            }
            else
                jLabel23.setText("");
            if(jTextField12.getText().equals(""))
            {
                jLabel24.setText("Fill this Field");
            }
            else
                jLabel24.setText("");
        }
        else
        {
            if(flag==0)
            {
                cname=jTextField2.getText();
                pdate=jTextField3.getText();
                paidamt=Integer.parseInt(jTextField4.getText());
                balamt=Integer.parseInt(jTextField5.getText());
                refid=Integer.parseInt(jTextField6.getText());
                saveupdate();
                
                try
                {
                    //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                    Scanner s=new Scanner(mob_purchased);
                    s.skip("Phone Name \tPhone Price \tPhone Color \tIMEI Number \n-------" +
                                        "--------------------------------------------------------------------------");
                    String mpurchased=s.nextLine().toString();
                    System.out.println(mpurchased);
                    Connection co;
                    Statement st;
                    Class.forName("com.mysql.jdbc.Driver");
                    co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                    st = co.createStatement();

                    PreparedStatement prp=co.prepareStatement("insert into newcustomer_details values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    prp.setString(1,Integer.toString(cid));
                    prp.setString(2,cname);
                    prp.setString(3,pdate);
                    prp.setString(4,Integer.toString(paidamt));
                    prp.setString(5,Integer.toString(balamt));
                    prp.setString(6,Integer.toString(refid));
                    prp.setString(7,dob);
                    prp.setString(8,Integer.toString(age));
                    prp.setString(9,sex);
                    prp.setString(10,dno);
                    prp.setString(11,street);
                    prp.setString(12,city);
                    prp.setString(13,state);
                    prp.setString(14,phno);
                    prp.setString(15,mob_purchased);

                    prp.executeUpdate();

                    JOptionPane.showMessageDialog(null,"Customer Details saved successfully");

                    
                    co.close();
                    dispose();

                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,"INVALID DATE, please select correct date"+e);
                    jComboBox1.setSelectedItem("01");
                    jComboBox2.setSelectedItem("jan");
                    jComboBox3.setSelectedItem("1910");
                }
                catch(NumberFormatException e )
                {
                    JOptionPane.showMessageDialog(null,"Error is:"+e);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Error is:"+e);
                }
            }
            else if(flag==1)
            {
                currentcid=Integer.parseInt(jTextField1.getText());
                totalbal=Integer.parseInt(jTextField14.getText());
                mob_purchased=jTextArea1.getText();
                try
                {
                    //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                    Connection co;
                    Statement st;
                    Class.forName("com.mysql.jdbc.Driver");
                    co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                    st = co.createStatement();

                    PreparedStatement prp=co.prepareStatement("update newcustomer_details set balamt=?, mob_purchased=? where cid=?");
                    prp.setString(1,Integer.toString(totalbal));
                    prp.setString(2,mob_purchased);
                    prp.setString(3,Integer.toString(currentcid));
                    prp.executeUpdate();

                    JOptionPane.showMessageDialog(null,"The Customer Details updated successfully");
                    
                    co.close();
                    dispose();

                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"The error is:"+e);
                }

            }
            else if(flag==2)
            {
                dispose();
            }
            else if(flag==3)
            {
                currentcid=Integer.parseInt(jTextField1.getText());
                saveupdate();
                try
                {
                    //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                    Connection co;
                    Statement st;
                    Class.forName("com.mysql.jdbc.Driver");
                    co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                    st = co.createStatement();

                    PreparedStatement prp=co.prepareStatement("update newcustomer_details set dob=?,age=?,gender=?,dno=?,street=?,city=?,state=?,phno=? where cid=?");
                    prp.setString(1,dob);
                    prp.setString(2,Integer.toString(age));
                    prp.setString(3,sex);
                    prp.setString(4,dno);
                    prp.setString(5,street);
                    prp.setString(6,city);
                    prp.setString(7,state);
                    prp.setString(8,phno);
                    prp.setString(9,Integer.toString(currentcid));
                    prp.executeUpdate();
                    JOptionPane.showMessageDialog(null,"The Customer Details Updated Successfully");
                    
                    co.close();
                    dispose();
                    

                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"The error is:"+e);
                }
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusGained
        // TODO add your handling code here:
        String temp=(String)jComboBox3.getSelectedItem();
        int birthyear=Integer.parseInt(temp);
        int thisyear=Integer.parseInt(year);
        System.out.println(birthyear+","+thisyear);
        int agefind=thisyear-birthyear;
        agefind=agefind-1;
        jTextField7.setText(Integer.toString(agefind));

    }//GEN-LAST:event_jTextField7FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedItem("01");
        jComboBox2.setSelectedItem("jan");
        jComboBox3.setSelectedItem("1910");
        jRadioButton1.setSelected(true);
        jTextField7.setText("");jLabel19.setText("");
        jTextField8.setText("");jLabel20.setText("");
        jTextField9.setText("");jLabel21.setText("");
        jTextField10.setText("");jLabel22.setText("");
        jTextField11.setText("");jLabel23.setText("");
        jTextField12.setText("");jLabel24.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JComboBox jComboBox1;
    public javax.swing.JComboBox jComboBox2;
    public javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabe;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
