/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MobileUpdate.java
 *
 * 
 */

package mobilestorenew;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
  
/**
 *
 * 
 */
public class MobileUpdate extends javax.swing.JFrame {

    /** Creates new form MobileUpdate */
    String model,name,cbox;
    
    int price,i1;
    
    String id,s1,s2,s3,s4,s5,pcolor,date;
    int a=0;
    int b=0;
    String imeino;
    String dt,year,ddate,mc,month;
    
    
    public MobileUpdate() {
        initComponents();
        setVisible(true);
        setSize(1270,740);
        setTitle("Update Mobile Details");
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        disflds();
        //JOptionPane.showMessageDialog(null,"Enter Phone Id (or) IMEI No. in the First Text Field");
        
    }
public void disflds()
{
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(true);
        jComboBox3.setEnabled(true);
        jComboBox4.setEnabled(true);
        jComboBox5.setEnabled(true);

        jTextField2.setEditable(true);
        jTextField3.setEditable(true);
        jTextField4.setEditable(true);

        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);

        jButton1.setEnabled(true);
}
public void clrcombocheck()
{
    jComboBox1.setSelectedItem("Nokia");
    jComboBox2.setSelectedItem("Red");
    jComboBox3.setSelectedItem("01");
    jComboBox4.setSelectedItem("jan");
    jComboBox5.setSelectedItem("2000");

    jCheckBox1.setSelected(true);
    jCheckBox2.setSelected(true);
    jCheckBox3.setSelected(true);
    jCheckBox4.setSelected(true);
    jCheckBox5.setSelected(true);
    jCheckBox6.setSelected(true);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Update Mobile Phone Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 20, 343, 50);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Mobile Details"));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mobile Phone Price");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 210, 160, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(290, 40, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mobile Phone Model");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 100, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Enter Phone Id (or) IMEI No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 40, 210, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(290, 160, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mobile Phone Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 150, 160, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(290, 220, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mobile Phone Color");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 280, 140, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(290, 340, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("IMEI No");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 340, 100, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green", "Blue", "Black", "White", "Cyan", "Yellow", "Orange", "Purple", "Pink", "Voilet", "Magenta" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(290, 280, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date of Manufacture");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 390, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Additional Accessories");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 440, 170, 20);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Charger ");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(290, 440, 80, 23);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setText("HeadSet ");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(400, 440, 80, 23);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setText("DataCable ");
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(290, 470, 100, 23);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox4.setText("Battery ");
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox4ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(400, 470, 80, 23);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox5.setText("MemoryCard ");
        jCheckBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox5ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(290, 500, 101, 23);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox6.setText("CD ");
        jCheckBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox6ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(400, 500, 50, 23);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(440, 40, 120, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nokia", "Samsung", "Lava", "MaxMobile", "Itel", "Vediocon", "Gionee", "Oppo", "Vivo", "Panasonic", "Intex", "Xolo", "Mi", "Micromax", "iBall", "Honor" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(290, 100, 140, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(290, 390, 50, 30);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(380, 390, 56, 30);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(490, 390, 60, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("(DD)");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 390, 28, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("(MM)");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(440, 390, 40, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("(YY)");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(550, 390, 24, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(210, 70, 590, 530);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(280, 20, 110, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Update Mobile Details");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(30, 20, 240, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(320, 610, 410, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        id=jTextField1.getText();

        model=(String)jComboBox1.getSelectedItem();
        name=jTextField2.getText();
        price=Integer.parseInt(jTextField3.getText());
        pcolor=(String)jComboBox2.getSelectedItem();
        imeino=jTextField4.getText();

        date=(String)jComboBox3.getSelectedItem();
        date+="-";
        date+=(String)jComboBox4.getSelectedItem();
        date+="-";
        date+=(String)jComboBox5.getSelectedItem();

        cbox=null;

        Boolean temp=(Boolean)jCheckBox1.isSelected();
            if(temp==true)
            {
                cbox+=(String)jCheckBox1.getText();
            }

            Boolean temp1=(Boolean)jCheckBox2.isSelected();
            if(temp1==true)
            {
                cbox+=(String)jCheckBox2.getText();
            }

            Boolean temp2=(Boolean)jCheckBox3.isSelected();
            if(temp2==true)
            {
                cbox+=(String)jCheckBox3.getText();
            }

            Boolean temp3=(Boolean)jCheckBox4.isSelected();
            if(temp3==true)
            {
                cbox+=(String)jCheckBox4.getText();
            }

            Boolean temp4=(Boolean)jCheckBox5.isSelected();
            if(temp4==true)
            {
                cbox+=(String)jCheckBox5.getText();
            }

            Boolean temp5=(Boolean)jCheckBox6.isSelected();
            if(temp5==true)
            {
                cbox+=(String)jCheckBox6.getText();
            }

            cbox=cbox.substring(4);
        try
	{

    		Connection co;
            Statement st;
            Class.forName("com.mysql.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
            st = co.createStatement();
					
                int a =st.executeUpdate("update newmobile_details set mobile_model="+"'"+model+"'"+","+"mobile_name="+"'"+name+"'"+","+"mobile_price="+"'"+price+"'"+","+"pcolor="+"'"+pcolor+"'"+","+"imeino="+"'"+imeino+"'"+","+"mdate="+"'"+date+"'"+","+"accessories="+"'"+cbox+"'"+ "where phone_id="+"'"+id+"'");
                //prp.setString(1,model);
                //prp.setString(2,name);
                //prp.setInt(3,price);
                //prp.setString(4,pcolor);
                //prp.setString(5,imeino);
                //prp.setString(6,date);
                //prp.setString(7,cbox);
                //prp.setString(8,id);
                //prp.executeUpdate();
                if(a==1)
                {
                    JOptionPane.showMessageDialog(null,"Mobile Phone details updated successfully");
                }
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");

                cbox=null;
                
                jTextField1.setEditable(true);

                disflds();

                clrcombocheck();
                jButton1.setEnabled(false);
		co.close();
	}
	catch(Exception e)
	{
		System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null,"error is:"+e);
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if(jTextField1.getText().equals(""))
        {
            jLabel10.setText("Entry is Must");
        }
        else
        {
                id=jTextField1.getText();
                try
                {
                        //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                        //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                    Connection co;
                    Statement st;
                    Class.forName("com.mysql.jdbc.Driver");
                    co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                    st = co.createStatement();
                        ResultSet res=st.executeQuery("select * from newmobile_details");
                        Boolean rec=res.next();
                        if(!rec)
                        {
                                JOptionPane.showMessageDialog(null,"There are no mobiles in the database");
                                jTextField1.setText("");
                        }
                        else
                        {
                                do
                                {
                                       s1=res.getString(1);
                                       s2=res.getString(2);
                                       s3=res.getString(3);
                                       i1=Integer.parseInt(res.getString(4));
                                       s4=res.getString(5);
                                       s5=res.getString(6);


                                       if(id.equalsIgnoreCase(s1) || id.equalsIgnoreCase(s5))
                                       {
                              
                                            jTextField1.setEditable(false);
                                            jTextField2.setEditable(true);
                                            jTextField2.setEditable(true);
                                            jTextField3.setEditable(true);
                                            jTextField4.setEditable(true);

                                            jComboBox1.setEnabled(true);
                                            jComboBox2.setEnabled(true);
                                            jComboBox3.setEnabled(true);
                                            jComboBox4.setEnabled(true);
                                            jComboBox5.setEnabled(true);

                                            jCheckBox1.setEnabled(true);
                                            jCheckBox2.setEnabled(true);
                                            jCheckBox3.setEnabled(true);
                                            jCheckBox4.setEnabled(true);
                                            jCheckBox5.setEnabled(true);
                                            jCheckBox6.setEnabled(true);
                                            jComboBox2.setEnabled(true);

                                            jLabel5.setText("          Mobile Phone Id");

                                            jLabel10.setText("");

                                            b=1;

                                            jTextField1.setText(s1);
                                            jComboBox1.setSelectedItem(s2);
                                            jTextField2.setText(s3);
                                            jTextField3.setText(Integer.toString(i1));
                                            jComboBox2.setSelectedItem(s4);
                                            jTextField4.setText(s5);

                                            dt=res.getDate(7).toString();
                                            System.out.println(dt);

                                            year=dt.substring(0,4);
                                            System.out.println(year);

                                            month=dt.substring(5,7);
                                            System.out.println(month);

                                            ddate=dt.substring(8,10);
                                            System.out.println(ddate);
                                            if(month.equals("01"))
                                            {
                                                mc="jan";
                                            }
                                            else if(month.equals("02"))
                                            {
                                                mc="feb";
                                            }
                                            else if(month.equals("03"))
                                            {
                                                mc="mar";
                                            }
                                            else if(month.equals("04"))
                                            {
                                                mc="apr";
                                            }
                                            else if(month.equals("05"))
                                            {
                                                mc="may";
                                            }
                                            else if(month.equals("06"))
                                            {
                                                mc="jun";
                                            }
                                            else if(month.equals("07"))
                                            {
                                                mc="jul";
                                            }
                                            else if(month.equals("08"))
                                            {
                                                mc="aug";
                                            }
                                            else if(month.equals("09"))
                                            {
                                                mc="sep";
                                            }
                                            else if(month.equals("10"))
                                            {
                                                mc="oct";
                                            }
                                            else if(month.equals("11"))
                                            {
                                                mc="nov";
                                            }
                                            else if(month.equals("12"))
                                            {
                                                mc="dec";
                                            }

                                            jComboBox3.setSelectedItem(ddate);
                                            jComboBox4.setSelectedItem(mc);
                                            jComboBox5.setSelectedItem(year);
                                            
                                            cbox=res.getString(8);
                                            Boolean cb1=cbox.contains("Charger");
                                            if(cb1==true)
                                            {
                                                jCheckBox1.setSelected(true);
                                            }
                                            else
                                            {                                               
                                            }

                                            Boolean cb2=cbox.contains("HeadSet");
                                            if(cb2==true)
                                            {
                                                jCheckBox2.setSelected(true);
                                            }
                                            else
                                            {                                               
                                            }

                                            Boolean cb3=cbox.contains("DataCable");
                                            if(cb3==true)
                                            {
                                                jCheckBox3.setSelected(true);
                                            }
                                            else
                                            {                                                
                                            }

                                            Boolean cb4=cbox.contains("Battery");
                                            if(cb4==true)
                                            {
                                                jCheckBox4.setSelected(true);
                                            }
                                            else
                                            {                                                
                                            }

                                            Boolean cb5=cbox.contains("MemoryCard");
                                            if(cb5==true)
                                            {
                                                jCheckBox5.setSelected(true);
                                            }
                                            else
                                            {                                                
                                            }

                                            Boolean cb6=cbox.contains("CD");
                                            if(cb6==true)
                                            {
                                                jCheckBox6.setSelected(true);
                                            }
                                            else
                                            {                                                
                                            }

                                            jButton1.setEnabled(false);
                                        }
                                }while(res.next());

                                if(b!=1)
                                {
                                    JOptionPane.showMessageDialog(null,"The mobile details does not exists in the database");
                                    jTextField1.setText("");
                                    jLabel10.setText("");
                                }
                        }
                        
                        co.close();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"There are no additional accessories for this mobile");
                    jButton1.setEnabled(false);
                }
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
        jTextField1.setEditable(true);

        disflds();

        clrcombocheck();

        b=0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox4ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jCheckBox4ItemStateChanged

    private void jCheckBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox5ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jCheckBox5ItemStateChanged

    private void jCheckBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox6ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jCheckBox6ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jTextField2KeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
