/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrintPreview.java
 *
 * Created on
 */

package mobilestorenew;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * 
 */
public class PrintPreview extends javax.swing.JFrame implements Printable{

    /** Creates new form PrintPreview */
    int a=0,d=0,flag=0;
    int price,amtpaid,reply1=1,reply,balamt,dpaidamt,dbalamt,drefid,dage;
    String refid="c",custrefid,cname,date,text,cid="r",dcid;
    String dcname,year1,month1,day1,mc1,dt1,dgender,ddno,dstreet,dcity,dstate,dphno;

    public PrintPreview() {
        initComponents();
        setVisible(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        setTitle("Print Preview");
        setSize(700,650);
        setResizable(false);
        setLocation(180,60);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MoolBoran", 1, 36)); // NOI18N
        jLabel1.setText("Anmol Communication");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 300, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bill Id :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 50, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bill Id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 40, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bill Date :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 40, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Bill Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 40, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Customer Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 90, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Customer Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 90, 270, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("---------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 130, 630, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Mobiles Purchased :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 170, 140, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(9);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 170, 410, 110);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total Price :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 310, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Total Price");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(190, 310, 100, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Amount Paid :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 350, 150, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Amount Paid ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(190, 350, 100, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 410, 100, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 100, 630, 480);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Near S.T. stand Hatkalngale.              Contact: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(160, 40, 340, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if(flag==0)
        {
            jButton1.setVisible(false);
            PrinterJob printJob = PrinterJob.getPrinterJob();
            
            if (printJob.printDialog())
            {
                try
                {
                    printJob.print();
                    printJob.setCopies(1);

                }
                catch(Exception PrintException)
                {
                    PrintException.printStackTrace();
                }
                printJob.cancel();
            }
            printJob.cancel();
            jButton1.setVisible(true);

            cname=jLabel7.getText();
            date=jLabel5.getText();
            amtpaid=Integer.parseInt(jLabel13.getText());
            price=Integer.parseInt(jLabel11.getText());
            balamt=price-amtpaid;


            if(price!=amtpaid)
            {
                dispose();
                while(reply1!=JOptionPane.YES_OPTION)
                {
                    reply=JOptionPane.showConfirmDialog(null,"Is this customer is new Customer or Existing Customer\n If new customer press Yes\n If Existing Customer Press No");
                    if(reply==JOptionPane.YES_OPTION)
                    {
                        while(!refid.equals(custrefid))
                        {
                            try
                            {
                                refid=JOptionPane.showInputDialog(null,"Enter Previous Customer Reference Id");
                                while(refid.equals(""))
                                {
                                    JOptionPane.showMessageDialog(null,"Please Enter Reference Id");
                                    refid=JOptionPane.showInputDialog(null,"Enter Previous Customer Referece Id");
                                }
                            }
                            catch(NullPointerException e)
                            {
                                int reply3=JOptionPane.showConfirmDialog(null,"Are you sure, you dont want to save customer details");
                                if(reply3==JOptionPane.YES_OPTION)
                                {
                                    JOptionPane.showMessageDialog(null,"The customer details are not saved");
                                    break;
                                }
                                if(reply3==JOptionPane.NO_OPTION)
                                {
                                    refid=JOptionPane.showInputDialog(null,"Enter Previous Customer Reference Id");
                                    while(refid.equals(""))
                                    {
                                        JOptionPane.showMessageDialog(null,"Please Enter Reference Id");
                                        refid=JOptionPane.showInputDialog(null,"Enter Previous Customer Referece Id");
                                    }
                                }
                                if(reply3==JOptionPane.CANCEL_OPTION)
                                {
                                    JOptionPane.showMessageDialog(null,"The customer details are not saved");
                                    break;
                                }
                            }
                            try
                            {
                                //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                                //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                                Connection con = DriverManager.getConnection("jdbc:ucanaccess://C://Users//abc//Documents//mobile.accdb");
                                Statement st=con.createStatement();
                                ResultSet res=st.executeQuery("select * from newcustomer_details");
                                Boolean rec=res.next();
                                if(!rec)
                                {
                                    custrefid="1";
                                    CreditCustomer cs=new CreditCustomer();
                                    cs.jTextField2.setText(cname);
                                    cs.jTextField3.setText(date);
                                    cs.jTextField4.setText(Integer.toString(amtpaid));
                                    cs.jTextField5.setText(Integer.toString(balamt));
                                    cs.jTextField6.setText(refid);
                                    cs.jTextArea1.setText("Phone Name \tPhone Price \tPhone Color \tIMEI Number \n-------" +
                                    "--------------------------------------------------------------------------"+text);
                                    cs.jTextField13.setVisible(false);
                                    cs.jTextField14.setVisible(false);
                                    cs.jLabel25.setVisible(false);
                                    cs.jLabel26.setVisible(false);
                                    cs.flag=0;
                                }
                                else
                                {
                                    do
                                    {
                                        custrefid=res.getString(1);
                                        if(refid.equals(custrefid))
                                        {
                                            CreditCustomer cs=new CreditCustomer();
                                            cs.jTextField2.setText(cname);
                                            cs.jTextField3.setText(date);
                                            cs.jTextField4.setText(Integer.toString(amtpaid));
                                            cs.jTextField5.setText(Integer.toString(balamt));
                                            cs.jTextField6.setText(refid);
                                            cs.jTextArea1.setText("Phone Name \tPhone Price \tPhone Color \tIMEI Number \n-------" +
                                            "--------------------------------------------------------------------------"+text);
                                            cs.jTextField13.setVisible(false);
                                            cs.jTextField14.setVisible(false);
                                            cs.jLabel25.setVisible(false);
                                            cs.jLabel26.setVisible(false);
                                            cs.flag=0;
                                            a=1;
                                            break;
                                        }
                                    }while(res.next());
                                    if(a==0)
                                    {
                                        JOptionPane.showMessageDialog(null,"The Reference Id is wrong, please enter correct Reference ID");
                                    }
                                }
                            }
                            catch(Exception e)
                            {
                                JOptionPane.showMessageDialog(null,"The error is:"+e);
                            }
                        }
                        break;
                    }
                    else if(reply==JOptionPane.NO_OPTION)
                    {
                        while(!cid.equals(dcid))
                        {
                            System.out.println("i came here");
                            try
                            {
                                cid=JOptionPane.showInputDialog(null,"Enter Customer Id");
                                while(cid.equals(""))
                                {
                                    JOptionPane.showMessageDialog(null,"Plese Enter Customer Id");
                                    cid=JOptionPane.showInputDialog(null,"Enter Customer Id");
                                }
                            }
                            catch(NullPointerException e)
                            {
                                int reply4=JOptionPane.showConfirmDialog(null,"Are you sure, you dont want to save customer details");
                                if(reply4==JOptionPane.YES_OPTION)
                                {
                                    JOptionPane.showMessageDialog(null,"The customer details are not saved");
                                    break;
                                }
                                if(reply4==JOptionPane.NO_OPTION)
                                {
                                    cid=JOptionPane.showInputDialog(null,"Enter Customer Id");
                                    while(cid.equals(""))
                                    {
                                        JOptionPane.showMessageDialog(null,"Plese Enter Customer Id");
                                        cid=JOptionPane.showInputDialog(null,"Enter Customer Id");
                                    }
                                }
                                if(reply4==JOptionPane.CANCEL_OPTION)
                                {
                                    JOptionPane.showMessageDialog(null,"The customer details are not saved");
                                    break;
                                }
                            }
                            try
                            {
                                //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                                //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                                Connection con = DriverManager.getConnection("jdbc:ucanaccess://C://Users//abc//Documents//mobile.accdb");
                                Statement st=con.createStatement();
                                ResultSet res=st.executeQuery("select * from newcustomer_details");
                                Boolean rec=res.next();
                                if(!rec)
                                {
                                }
                                else
                                {
                                    do
                                    {
                                        dcid=res.getString(1);
                                        dcname=res.getString(2);
                                        dpaidamt=res.getInt(4);
                                        dbalamt=res.getInt(5);
                                        drefid=res.getInt(6);

                                        java.sql.Date ddob=res.getDate(7);
                                        dt1=ddob.toString();
                                        year1=dt1.substring(0,4);
                                        month1=dt1.substring(5,7);
                                        day1=dt1.substring(8,10);
                                        if(month1.equals("01"))
                                        {
                                            mc1="jan";
                                        }
                                        else if(month1.equals("02"))
                                        {
                                            mc1="feb";
                                        }
                                        else if(month1.equals("03"))
                                        {
                                            mc1="mar";
                                        }
                                        else if(month1.equals("04"))
                                        {
                                            mc1="apr";
                                        }
                                        else if(month1.equals("05"))
                                        {
                                            mc1="may";
                                        }
                                        else if(month1.equals("06"))
                                        {
                                            mc1="jun";
                                        }
                                        else if(month1.equals("07"))
                                        {
                                            mc1="jul";
                                        }
                                        else if(month1.equals("08"))
                                        {
                                            mc1="aug";
                                        }
                                        else if(month1.equals("09"))
                                        {
                                            mc1="sep";
                                        }
                                        else if(month1.equals("10"))
                                        {
                                            mc1="oct";
                                        }
                                        else if(month1.equals("11"))
                                        {
                                            mc1="nov";
                                        }
                                        else if(month1.equals("12"))
                                        {
                                            mc1="dec";
                                        }

                                        dage=res.getInt(8);
                                        dgender=res.getString(9);
                                        ddno=res.getString(10);
                                        dstreet=res.getString(11);
                                        dcity=res.getString(12);
                                        dstate=res.getString(13);
                                        dphno=res.getString(14);
                                        String dmob_purchase=res.getString(15);
                                        dmob_purchase+=text;
                                        if(cid.equals(dcid))
                                        {
                                            CreditCustomer cs=new CreditCustomer();
                                            cs.jComboBox1.setEnabled(false);
                                            cs.jComboBox2.setEnabled(false);
                                            cs.jComboBox3.setEnabled(false);
                                            cs.jTextField7.setEditable(false);
                                            cs.jRadioButton1.setEnabled(false);
                                            cs.jRadioButton2.setEnabled(false);
                                            cs.jTextField8.setEditable(false);
                                            cs.jTextField9.setEditable(false);
                                            cs.jTextField10.setEditable(false);
                                            cs.jTextField11.setEditable(false);
                                            cs.jTextField12.setEditable(false);
                                            cs.jButton1.setText("Update Customer Details");

                                            cs.jTextField1.setText(dcid);
                                            cs.jTextField2.setText(dcname);
                                            cs.jTextField3.setText(date);
                                            cs.jTextField4.setText(Integer.toString(amtpaid));
                                            cs.jTextField5.setText(Integer.toString(balamt));
                                            cs.jTextField6.setText(Integer.toString(drefid));
                                            cs.jTextArea1.setText(dmob_purchase);
                                            cs.jComboBox1.setSelectedItem(day1);
                                            cs.jComboBox2.setSelectedItem(mc1);
                                            cs.jComboBox3.setSelectedItem(year1);
                                            cs.jTextField7.setText(Integer.toString(dage));
                                            if(dgender.equalsIgnoreCase("male"))
                                                cs.jRadioButton1.setSelected(true);
                                            if(dgender.equalsIgnoreCase("female"))
                                                cs.jRadioButton2.setSelected(true);

                                            cs.jTextField8.setText(ddno);
                                            cs.jTextField9.setText(dstreet);
                                            cs.jTextField10.setText(dcity);
                                            cs.jTextField11.setText(dstate);
                                            cs.jTextField12.setText(dphno);
                                            cs.jTextField13.setText(Integer.toString(dbalamt));

                                            int totalamt=dbalamt+balamt;
                                            cs.jTextField14.setText(Integer.toString(totalamt));

                                            cs.flag=1;
                                            d=1;
                                            break;
                                        }
                                    }while(res.next());
                                    if(d==0)
                                    {
                                        JOptionPane.showMessageDialog(null,"Please enter correct Customer Id");
                                    }
                                }
                            }
                            catch(Exception e)
                            {
                                JOptionPane.showMessageDialog(null,"The error is:"+e);
                            }
                        }
                        break;
                    }
                    else if(reply==JOptionPane.CANCEL_OPTION)
                    {
                        reply1=JOptionPane.showConfirmDialog(null,"Are you sure you dont want to save customer details");

                        if(reply1==JOptionPane.YES_OPTION)
                        {
                            JOptionPane.showMessageDialog(null,"The Customer Details are not saved");
                        }
                        if(reply1==JOptionPane.NO_OPTION)
                        {
                        }
                        if(reply1==JOptionPane.CANCEL_OPTION)
                        {
                            JOptionPane.showMessageDialog(null,"The customer details are not saved");
                            break;
                        }

                    }
                }
            }
            else
            {
                dispose();
            }
        }
        else if(flag==1)
        {
            jButton1.setVisible(false);
            PrinterJob printJob = PrinterJob.getPrinterJob();
            
            if (printJob.printDialog())
            {
                try
                {
                    printJob.print();
                    printJob.setCopies(1);

                }
                catch(Exception PrintException)
                {
                    PrintException.printStackTrace();
                }
                printJob.cancel();
            }
            printJob.cancel();
            jButton1.setVisible(true);

        }

    }//GEN-LAST:event_jButton1ActionPerformed
public int print(Graphics g, PageFormat pf, int pi) throws PrinterException
{
    Graphics2D g2 = (Graphics2D) g;
    g2.translate(pf.getImageableX()+5, pf.getImageableY()+5);
    Font  f = new Font("Monospaced",Font.PLAIN,12);
    g2.setFont (f);
    paint (g2);
    return Printable.PAGE_EXISTS;
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintPreview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
