/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SalesReports.java
 *
 * 
 */

package mobilestorenew;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.*;
import java.sql.*;
import javax.swing.*;



/**
 *
 * 
 */
public class SalesReports extends javax.swing.JFrame implements Printable {

    /** Creates new form SalesReports */
    String text="";
    int a=0,flag;
    int countsales=0,totalamt=0;
    public SalesReports() {
        initComponents();
        setSize(1270,740);
        setTitle("Sales Reports");
        jTextArea1.setEditable(false);
        setVisible(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH); 

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sales Reports");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 10, 320, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 610, 110, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 610, 100, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(10);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 140, 910, 440);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 80, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select Month");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 80, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Select Year");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 80, 90, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(520, 80, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Generate Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(720, 70, 160, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        PrinterJob printJob = PrinterJob.getPrinterJob();
        
        if (printJob.printDialog())
        {
            try
            {
                printJob.print();
                printJob.setCopies(1);

            }
            catch(Exception PrintException)
            {
                PrintException.printStackTrace();
            }
            printJob.cancel();
        }
        printJob.cancel();
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        text="";
        a=0;
        String month=(String)jComboBox1.getSelectedItem();
        String year=(String)jComboBox2.getSelectedItem();

        try
            {
                //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
               Connection co;
            Statement st;
            Class.forName("com.mysql.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
            st = co.createStatement();
                ResultSet res=st.executeQuery("select * from newbill");
                Boolean rec=res.next();
                if(rec==false)
                {
                    JOptionPane.showMessageDialog(null,"There are no sales on that month");
                }
                else
                {
                    
                    if(flag==0)
                    {
                        do
                        {
                            String dbid = res.getString(1);
                            String dbdate = res.getString(2);
                            String bdate = dbdate;
                            System.out.println(bdate);
                            String dmonth=bdate.substring(3,6);
                            
                            
                            String dyear=bdate.substring(7,11);
                            System.out.println(dmonth+","+dyear);
                            String mc1="";
                            if (dmonth.equalsIgnoreCase("jan"))
                            {
                                mc1 = "jan";
                            } 
                            else if (dmonth.equalsIgnoreCase("feb"))
                            {
                                    mc1 = "feb";
                            } else if (dmonth.equalsIgnoreCase("mar"))
                            {
                                    mc1 = "mar";
                            } else if (dmonth.equalsIgnoreCase("apr"))
                            {
                                    mc1 = "apr";
                            } else if (dmonth.equalsIgnoreCase("may"))
                            {
                                    mc1 = "may";
                            } else if (dmonth.equalsIgnoreCase("jun"))
                            {
                                    mc1 = "jun";
                            } else if (dmonth.equalsIgnoreCase("jul"))
                            {
                                    mc1 = "jul";
                            } else if (dmonth.equalsIgnoreCase("aug"))
                            {
                                    mc1 = "aug";
                            } else if (dmonth.equalsIgnoreCase("sep"))
                            {
                                    mc1 = "sep";
                            } else if (dmonth.equalsIgnoreCase("oct"))
                            {
                                    mc1 = "oct";
                            } else if (dmonth.equalsIgnoreCase("nov"))
                            {
                                    mc1 = "nov";
                            } else if (dmonth.equalsIgnoreCase("dev"))
                            {
                                    mc1 = "dec";
                            }

                            String dcname = res.getString(3);
                            int dprice = Integer.parseInt(res.getString(4));
                            int damtpaid= Integer.parseInt(res.getString(5));
                            String mob_purchased = res.getString(7);

                            if(mc1.equalsIgnoreCase(month) && dyear.equalsIgnoreCase(year))
                            {
                                countsales++;
                                totalamt+=damtpaid;
                                text+="\n"+dbid+" \t"+bdate+" \t"+dcname+" \t\t"+dprice+" \t"+damtpaid+" \t"+mob_purchased+" \n";
                                jTextArea1.setText("Bill Id \tBill Date \tCustomerName \t\tTotalPrice \tAmountPaid \tMobiles Purchased \n"+
                                "-----------------------------------------------------------------------------------------------------" +
                                "-----------------------------------------------------------------------------"+text+"\n--------------------------------------------------------------------------------------------"+
                                "-----------------------------------------------------------------------------\n\n\t\t Total No. Of Sales: "+countsales+"\tTotal Amount Collected: "+totalamt);
                                a=1;
                            }
                        }while(res.next());
                        countsales=0;
                        totalamt=0;
                        
                    }
                    if(flag==1)
                    {
                        do
                        {
                            String dbid = res.getString(1);
                            String dbdate = res.getString(2);
                            String bdate = dbdate.toString();
                            String dyear=bdate.substring(7,11);;
                            String dcname = res.getString(3);
                            int dprice = Integer.parseInt(res.getString(4));
                            int damtpaid =Integer.parseInt(res.getString(5));
                            String mob_purchased = res.getString(7);
                            if(dyear.equalsIgnoreCase(year))
                            {

                                countsales++;
                                totalamt+=damtpaid;
                                text+="\n"+dbid+" \t"+bdate+" \t"+dcname+" \t\t"+dprice+" \t"+damtpaid+" \t"+mob_purchased+" \n";
                                jTextArea1.setText("Bill Id \tBill Date \tCustomerName \t\tTotalPrice \tAmountPaid \tMobiles Purchased \n"+
                                "-----------------------------------------------------------------------------------------------------" +
                                "-----------------------------------------------------------------------------"+text+"\n--------------------------------------------------------------------------------------------"+
                                "-----------------------------------------------------------------------------\n\n\t\t Total No. Of Sales: "+countsales+"\tTotal Amount Collected: "+totalamt);
                                countsales=0;
                                totalamt=0;
                                a=1;
                            }

                        }
                        while(res.next());
                        
                    }
                    if(a==0)
                    {
                        JOptionPane.showMessageDialog(null,"There are no sales on that particular month");
                        jTextArea1.setText("");
                    }
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is4:"+e);
            }


    }//GEN-LAST:event_jButton3ActionPerformed
public int print(Graphics g, PageFormat pf, int pi) throws PrinterException
{
    Graphics2D g2 = (Graphics2D) g;
    g2.translate(pf.getImageableX()+5, pf.getImageableY()+5);
    Font  f = new Font("Monospaced",Font.PLAIN,12);
    g2.setFont (f);
    paint (g2);
    return Printable.PAGE_EXISTS;
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JComboBox jComboBox1;
    public javax.swing.JComboBox jComboBox2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
