/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchCustomer.java
 *
 * 
 */

package mobilestorenew;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @
 */
public class SearchCustomer extends javax.swing.JFrame {

    /** Creates new form SearchCustomer */
    int flag=0,rows=0,a=0,b=0;
    String cid;
    Object data[][];
    JTable table;
    JScrollPane jsp;
    ResultSet res;
    ResultSet rs;
    public SearchCustomer() {
        initComponents();
        setVisible(true);
        setSize(1270,740);
        setTitle("Search Customer");
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
    }
    public void tabledisp()
    {
        try
                {

                    data=new Object[rows][15];
                    Object[] colheads={"Custmer Id","Customer Name","Purchase Date","Paid Amount","Balance Amount","Reference Id","Date Of Birth","Age","Gender","Door No","Street","City","State","Phone No","Mobiles Purchased"};


                    //Class.forName("sun.jdbc.odbc.JdbcOdbc");
                    //Connection con=DriverManager.getConnection("Jdbc:Odbc:mobileDSN","scott","tiger");
                   Connection co;
                    Statement st;
                     Class.forName("com.mysql.jdbc.Driver");
                     co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                        st = co.createStatement();

                    rs=st.executeQuery("select * from csearch");
                    for(int i=0;i<rows;i++)
                    {
                            rs.next();
                            for(int j=0;j<15;j++)
                            {
                                data [i][j]=rs.getString(j+1);
                                System.out.println(data[i][j]);
                            }
                    }
                    table=new JTable(data,colheads);

                    int v=ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED;
                    int h=ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED;
                    jsp=new JScrollPane(table,v,h);
                    jsp.setBounds(70,380,900,240);
                    jPanel2.add(jsp);
                    add(jsp);
                    System.out.println("hai we came here");
                    rows=0;
                    st.close();
                    co.close();

                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"here the error is:1"+e);
                }

    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Search Field");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 40, 90, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 40, 160, 30);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(380, 40, 100, 30);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(" Search By Customer Id");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(90, 110, 210, 25);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jRadioButton2.setText(" Search By Customer Name");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(90, 160, 230, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 90, 500, 240);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("Search Customer Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 320, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 180, 120, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton2.setText("Cancel");
        getContentPane().add(jButton2);
        jButton2.setBounds(770, 180, 100, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Results"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 350, 960, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(""))
        {
            jLabel3.setText("Entry Is Must");
            jTextField1.setText("");
        }
        else
        {
            jLabel3.setText("");
            cid=jTextField1.getText();
            if(flag==0)
            {
                try
                {
                    //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                   Connection co;
                    Statement st;
                    Class.forName("com.mysql.jdbc.Driver");
                    co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                    st = co.createStatement();
                    //st.executeUpdate("delete csearch");
                    res=st.executeQuery("select * from newcustomer_details where cid="+"'"+cid+"'");
                    Boolean rec=res.next();
                    if(rec==false)
                    {
                        JOptionPane.showMessageDialog(null,"There are no customers exists");
                        jTextField1.setText("");
                    }
                    else
                    {
                        do
                        {
                            String dcid=res.getString(1);
                            String dcname=res.getString(2);
                            System.out.println(dcname);
                            String dt=res.getString(3);
                            String dd=dt;
                            String year=dd.substring(0,4);
                            String month=dd.substring(5,7);
                            String day=dd.substring(8,10);
                            String mc="";
                            if(month.equals("01"))
                            {
                                mc="jan";
                            }
                            else if(month.equals("02"))
                            {
                                mc="feb";
                            }
                            else if(month.equals("03"))
                            {
                                mc="mar";
                            }
                            else if(month.equals("04"))
                            {
                                mc="apr";
                            }
                            else if(month.equals("05"))
                            {
                                mc="may";
                            }
                            else if(month.equals("06"))
                            {
                                mc="jun";
                            }
                            else if(month.equals("07"))
                            {
                                mc="jul";
                            }
                            else if(month.equals("08"))
                            {
                                mc="aug";
                            }
                            else if(month.equals("09"))
                            {
                                mc="sep";
                            }
                            else if(month.equals("10"))
                            {
                                mc="oct";
                            }
                            else if(month.equals("11"))
                            {
                                mc="nov";
                            }
                            else if(month.equals("12"))
                            {
                                mc="dec";
                            }
                            String date=day+"-"+mc+"-"+year;

                            int dpaidamt=Integer.parseInt(res.getString(4));
                            int dbalamt=Integer.parseInt(res.getString(5));
                            int drefid=Integer.parseInt(res.getString(6));

                            String dob=res.getString(7);

                            String ddob=dob;
                            String year1=ddob.substring(0,4);
                            String month1=ddob.substring(5,7);
                            String day1=ddob.substring(8,10);

                            String mc1="";
                            if(month1.equals("01"))
                            {
                                mc1="jan";
                            }
                            else if(month1.equals("02"))
                            {
                                mc1="feb";
                            }
                            else if(month1.equals("03"))
                            {
                                mc1="mar";
                            }
                            else if(month1.equals("04"))
                            {
                                mc1="apr";
                            }
                            else if(month1.equals("05"))
                            {
                                mc1="may";
                            }
                            else if(month1.equals("06"))
                            {
                                mc1="jun";
                            }
                            else if(month1.equals("07"))
                            {
                                mc1="jul";
                            }
                            else if(month1.equals("08"))
                            {
                                mc1="aug";
                            }
                            else if(month1.equals("09"))
                            {
                                mc1="sep";
                            }
                            else if(month1.equals("10"))
                            {
                                mc1="oct";
                            }
                            else if(month1.equals("11"))
                            {
                                mc1="nov";
                            }
                            else if(month1.equals("12"))
                            {
                                mc1="dec";
                            }

                            String date1=day1+"-"+mc1+"-"+year1;

                            int dage=Integer.parseInt(res.getString(8));
                            String dgender=res.getString(9);
                            String ddno=res.getString(10);
                            String dstreet=res.getString(11);
                            String dcity=res.getString(12);
                            String dstate=res.getString(13);
                            String dphno=res.getString(14);
                            String dmob_purchased=res.getString(15);

                            /*if(cid.equalsIgnoreCase(dcid))
                            {
                                PreparedStatement prp=co.prepareStatement("insert into csearch values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                                prp.setString(1,dcid);
                                prp.setString(2,dcname);
                                prp.setString(3,date);
                                prp.setString(4,Integer.toString(dpaidamt));
                                prp.setString(5,Integer.toString(dbalamt));
                                prp.setString(6,Integer.toString(drefid));
                                prp.setString(7,date1);
                                prp.setString(8,Integer.toString(dage));
                                prp.setString(9,dgender);
                                prp.setString(10,ddno);
                                prp.setString(11,dstreet);
                                prp.setString(12,dcity);
                                prp.setString(13,dstate);
                                prp.setString(14,dphno);
                                prp.setString(15,dmob_purchased);

                                prp.executeUpdate();
                                rows++;
                                System.out.println(rows);
                                System.out.println("i came here");

                                a=1;

                                jTextField1.setText("");

                            }*/
                            rows++;
                            a=1;
                            
                        }while(res.next());
                        data=new Object[rows][15];
                    Object[] colheads={"Custmer Id","Customer Name","Purchase Date","Paid Amount","Balance Amount","Reference Id","Date Of Birth","Age","Gender","Door No","Street","City","State","Phone No","Mobiles Purchased"};


                    //Class.forName("sun.jdbc.odbc.JdbcOdbc");
                    //Connection con=DriverManager.getConnection("Jdbc:Odbc:mobileDSN","scott","tiger");
                     Class.forName("com.mysql.jdbc.Driver");
                     co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                        st = co.createStatement();

                    rs=st.executeQuery("select * from newcustomer_details where cid="+"'"+cid+"'");
                    for(int i=0;i<rows;i++)
                    {
                            rs.next();
                            for(int j=0;j<15;j++)
                            {
                                data [i][j]=rs.getString(j+1);
                                System.out.println(data[i][j]);
                            }
                    }
                    table=new JTable(data,colheads);

                    int v=ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED;
                    int h=ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED;
                    jsp=new JScrollPane(table,v,h);
                    jsp.setBounds(70,380,900,240);
                    jPanel2.add(jsp);
                    add(jsp);
                    System.out.println("hai we came here");
                    rows=0;
                    st.close();
                    co.close();
                        if(a==0)
                        {
                            JOptionPane.showMessageDialog(null,"The customer ID does not exists");
                            jTextField1.setText("");
                        }
                    }
                    co.close();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"The error is:2"+e);
                }
                //tabledisp();
            }
            if(flag==1)
            {
                jLabel3.setText("");
                cid=jTextField1.getText();
                try
                {
                    //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    //Connection con=DriverManager.getConnection("jdbc:odbc:mobileDSN","scott","tiger");
                    Connection co;
                    Statement st;
                    Class.forName("com.mysql.jdbc.Driver");
                    co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                    st = co.createStatement();
                    //st.executeUpdate("delete csearch");
                    res=st.executeQuery("select * from newcustomer_details where cname="+"'"+cid+"'");
                    Boolean rec=res.next();
                    if(rec==false)
                    {
                        JOptionPane.showMessageDialog(null,"There are no customers exists");
                        jTextField1.setText("");
                    }
                    else
                    {
                        do
                        {
                            String dcid=res.getString(1);
                            String dcname=res.getString(2);

                            String dt=res.getString(3);
                            String dd=dt;
                            String year=dd.substring(0,4);
                            String month=dd.substring(5,7);
                            String day=dd.substring(8,10);
                            String mc="";
                            if(month.equals("01"))
                            {
                                mc="jan";
                            }
                            else if(month.equals("02"))
                            {
                                mc="feb";
                            }
                            else if(month.equals("03"))
                            {
                                mc="mar";
                            }
                            else if(month.equals("04"))
                            {
                                mc="apr";
                            }
                            else if(month.equals("05"))
                            {
                                mc="may";
                            }
                            else if(month.equals("06"))
                            {
                                mc="jun";
                            }
                            else if(month.equals("07"))
                            {
                                mc="jul";
                            }
                            else if(month.equals("08"))
                            {
                                mc="aug";
                            }
                            else if(month.equals("09"))
                            {
                                mc="sep";
                            }
                            else if(month.equals("10"))
                            {
                                mc="oct";
                            }
                            else if(month.equals("11"))
                            {
                                mc="nov";
                            }
                            else if(month.equals("12"))
                            {
                                mc="dec";
                            }
                            String date=day+"-"+mc+"-"+year;

                            int dpaidamt=Integer.parseInt(res.getString(4));
                            int dbalamt=Integer.parseInt(res.getString(5));
                            int drefid=Integer.parseInt(res.getString(6));

                            String dob=res.getString(7);

                            String ddob=dob.toString();
                            String year1=ddob.substring(0,4);
                            String month1=ddob.substring(5,7);
                            String day1=ddob.substring(8,10);

                            String mc1="";
                            if(month1.equals("01"))
                            {
                                mc1="jan";
                            }
                            else if(month1.equals("02"))
                            {
                                mc1="feb";
                            }
                            else if(month1.equals("03"))
                            {
                                mc1="mar";
                            }
                            else if(month1.equals("04"))
                            {
                                mc1="apr";
                            }
                            else if(month1.equals("05"))
                            {
                                mc1="may";
                            }
                            else if(month1.equals("06"))
                            {
                                mc1="jun";
                            }
                            else if(month1.equals("07"))
                            {
                                mc1="jul";
                            }
                            else if(month1.equals("08"))
                            {
                                mc1="aug";
                            }
                            else if(month1.equals("09"))
                            {
                                mc1="sep";
                            }
                            else if(month1.equals("10"))
                            {
                                mc1="oct";
                            }
                            else if(month1.equals("11"))
                            {
                                mc1="nov";
                            }
                            else if(month1.equals("12"))
                            {
                                mc1="dec";
                            }

                            String date1=day1+"-"+mc1+"-"+year1;

                            int dage=Integer.parseInt(res.getString(8));
                            String dgender=res.getString(9);
                            String ddno=res.getString(10);
                            String dstreet=res.getString(11);
                            String dcity=res.getString(12);
                            String dstate=res.getString(13);
                            String dphno=res.getString(14);
                            String dmob_purchased=res.getString(15);

                            /*if(cid.equals(dcname))
                            {
                                PreparedStatement prp=co.prepareStatement("insert into csearch values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                                prp.setString(1,dcid);
                                prp.setString(2,dcname);
                                prp.setString(3,date);
                                prp.setString(4,Integer.toString(dpaidamt));
                                prp.setString(5,Integer.toString(dbalamt));
                                prp.setString(6,Integer.toString(drefid));
                                prp.setString(7,date1);
                                prp.setString(8,Integer.toString(dage));
                                prp.setString(9,dgender);
                                prp.setString(10,ddno);
                                prp.setString(11,dstreet);
                                prp.setString(12,dcity);
                                prp.setString(13,dstate);
                                prp.setString(14,dphno);
                                prp.setString(15,dmob_purchased);
                                prp.executeUpdate();
                                rows++;
                                System.out.println(rows);
                                System.out.println("i came here");

                                b=1;

                                jTextField1.setText("");

                            }*/
                            rows++;
                            b=1;
                            
                        }while(res.next());
                        data=new Object[rows][15];
                    Object[] colheads={"Custmer Id","Customer Name","Purchase Date","Paid Amount","Balance Amount","Reference Id","Date Of Birth","Age","Gender","Door No","Street","City","State","Phone No","Mobiles Purchased"};


                    //Class.forName("sun.jdbc.odbc.JdbcOdbc");
                    //Connection con=DriverManager.getConnection("Jdbc:Odbc:mobileDSN","scott","tiger");
                     Class.forName("com.mysql.jdbc.Driver");
                     co = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","root");
                        st = co.createStatement();

                    rs=st.executeQuery("select * from newcustomer_details where cname="+"'"+cid+"'");
                    for(int i=0;i<rows;i++)
                    {
                            rs.next();
                            for(int j=0;j<15;j++)
                            {
                                data [i][j]=rs.getString(j+1);
                                System.out.println(data[i][j]);
                            }
                    }
                    table=new JTable(data,colheads);

                    int v=ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED;
                    int h=ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED;
                    jsp=new JScrollPane(table,v,h);
                    jsp.setBounds(70,380,900,240);
                    jPanel2.add(jsp);
                    add(jsp);
                    System.out.println("hai we came here");
                    rows=0;
                    st.close();
                    co.close();
                        if(b==0)
                        {
                            JOptionPane.showMessageDialog(null,"The customer Name does not exists");
                            jTextField1.setText("");
                        }
                    }
                  
                    co.close();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"The error is:3"+e);
                }
                //tabledisp();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jsp.setVisible(false);
        a=0;
        b=0;
    }//GEN-LAST:event_jTextField1FocusGained

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        flag=0;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        flag=1;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
